apiVersion: v1
kind: Service
metadata:
  name: test-app-service
  namespace: test-app-namespace
  labels:
    app: test-app
spec:
  selector:
    app: test-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30001
  type: NodePort